import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import ts from 'typescript';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'orbita-test-'));process.env.DATA_DIR=path.join(temp,'data');process.env.MIGRATIONS_DIR=path.resolve('drizzle');process.env.SETUP_TOKEN='a-test-only-setup-token';process.env.APP_ORIGIN='https://orbita.test';
const mod=path.join(temp,'modules');fs.mkdirSync(mod);
for(const name of ['storage','auth','server','integrations'])compile('lib/'+name+'.ts',name);
for(const name of ['auth','brands','posts','workspace','invites','media'])compile('app/api/'+name+'/route.ts','route-'+name);compile('app/api/jobs/route.ts','route-jobs');
function compile(source,name){const input=fs.readFileSync(source,'utf8').replace(/'@\/lib\/(\w+)'/g,"'./$1.mjs'").replace(/'\.\/(storage|auth|server)'/g,"'./$1.mjs'");fs.writeFileSync(path.join(mod,name+'.mjs'),ts.transpileModule(input,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText)}
const modules={};for(const name of ['auth','brands','posts','workspace','invites','media'])modules[name]=await import('file://'+path.join(mod,'route-'+name+'.mjs'));modules.jobs=await import('file://'+path.join(mod,'route-jobs.mjs'));const server=await import('file://'+path.join(mod,'server.mjs'));
let ownerCookie,clientCookie,brandId,postId,invite;
async function call(name,body,cookie='',method='POST',extra={}){const req=new Request('https://orbita.test/api/'+name,{method,headers:{'Content-Type':'application/json',Origin:process.env.APP_ORIGIN,Cookie:cookie,...extra},...(method==='GET'?{}:{body:JSON.stringify(body)})});const r=await modules[name][method](req);return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
await test('public traffic cannot impersonate the old hosting identity',async()=>{const r=await call('workspace',null,'','GET',{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@test.com'});assert.equal(r.status,401)});
await test('bootstrap requires setup token; session is secure',async()=>{let r=await call('auth',{action:'register',email:'owner@test.com',password:'Strong-password-123'});assert.equal(r.status,403);r=await call('auth',{action:'register',email:'owner@test.com',password:'Strong-password-123',setupToken:process.env.SETUP_TOKEN});assert.equal(r.status,200);ownerCookie=r.cookie;assert.match(ownerCookie,/orbita_session=/);const again=await call('auth',{action:'register',email:'intruder@test.com',password:'Strong-password-123',setupToken:process.env.SETUP_TOKEN});assert.equal(again.status,409)});
await test('brand, invite and real customer account work',async()=>{const b=await call('brands',{name:'Client Brand',email:'client@test.com'},ownerCookie);assert.equal(b.status,200);brandId=b.body.id;const i=await call('invites',{brand_id:brandId},ownerCookie);assert.equal(i.status,200);invite=new URL(i.body.url).searchParams.get('convite');const bad=await call('auth',{action:'register',email:'wrong@test.com',password:'Strong-password-123',invite});assert.equal(bad.status,403);const good=await call('auth',{action:'register',email:'client@test.com',password:'Strong-password-123',invite});assert.equal(good.status,200);clientCookie=good.cookie;const restricted=await call('brands',{name:'Unauthorized'},clientCookie);assert.equal(restricted.status,403)});
await test('content persists and client approval comments are kept in history',async()=>{const p=await call('posts',{brand_id:brandId,title:'Launch',caption:'Approved content',platform:'instagram',format:'image',media:[],status:'review',scheduled_at:new Date(Date.now()+86400000).toISOString()},ownerCookie);assert.equal(p.status,200);postId=p.body.id;const w=await call('workspace',null,clientCookie,'GET');assert.equal(w.body.posts.length,1);const a=await call('posts',{id:postId,revision:1,action:'approve',comment:'Pode publicar às 18h.'},clientCookie,'PATCH');assert.equal(a.status,200);const after=await call('workspace',null,ownerCookie,'GET');assert.equal(after.body.posts[0].history.at(-1).comment,'Pode publicar às 18h.')});
await test('editing invalidates prior approval and stale decision',async()=>{const p=await call('posts',{id:postId,revision:1,action:'edit',title:'Edited',caption:'New content',platform:'instagram',format:'image',media:[],scheduled_at:new Date(Date.now()+86400000).toISOString()},ownerCookie,'PATCH');assert.equal(p.status,200);const old=await call('posts',{id:postId,revision:1,action:'approve'},clientCookie,'PATCH');assert.equal(old.status,409);const w=await call('workspace',null,ownerCookie,'GET');assert.equal(w.body.posts[0].status,'review')});
await test('cross-origin mutation blocked',async()=>{const r=await call('posts',{id:postId,revision:2,action:'approve'},clientCookie,'PATCH',{Origin:'https://evil.test'});assert.equal(r.status,403)});
await test('Story poll pauses at scheduled time and requires an explicit publish confirmation',async()=>{process.env.SCHEDULER_ENABLED='true';process.env.SCHEDULER_SECRET='scheduler-test';await server.db().prepare('INSERT INTO connections(id,brand_id,provider,account_id,name,token,updated) VALUES(?,?,?,?,?,?,?)').bind('poll-connection',brandId,'instagram_direct','ig-account','Client IG','encrypted-token',new Date().toISOString()).run();await server.bucket().put('poll-story',new TextEncoder().encode('story media').buffer);await server.db().prepare('INSERT INTO assets(id,brand_id,name,type,size,share_key) VALUES(?,?,?,?,?,?)').bind('poll-story',brandId,'story.png','image/png',11,'share-poll-story').run();const p=await call('posts',{brand_id:brandId,title:'Story com enquete',caption:'',platform:'instagram',format:'story',media:['poll-story'],poll_question:'Qual sabor?',poll_option_a:'Chocolate',poll_option_b:'Baunilha',has_poll:true,status:'review',scheduled_at:new Date(Date.now()+86400000).toISOString()},ownerCookie);assert.equal(p.status,200);const id=p.body.id;const approve=await call('posts',{id,revision:1,action:'approve'},clientCookie,'PATCH');assert.equal(approve.status,200);await server.db().prepare('UPDATE posts SET scheduled_at=? WHERE id=?').bind(new Date(Date.now()-1000).toISOString(),id).run();const job=await call('jobs',{},'','POST',{Authorization:'Bearer scheduler-test'});assert.equal(job.status,200);const held=await call('workspace',null,ownerCookie,'GET');const poll=held.body.posts.find(x=>x.id===id);assert.equal(poll.status,'needs_action');const done=await call('posts',{id,revision:1,action:'mark-published'},ownerCookie,'PATCH');assert.equal(done.status,200);const finished=await call('workspace',null,clientCookie,'GET');assert.equal(finished.body.posts.find(x=>x.id===id).status,'published')});
await test('logout revokes persistent session',async()=>{const r=await call('auth',{action:'logout'},clientCookie);assert.equal(r.status,200);const w=await call('workspace',null,clientCookie,'GET');assert.equal(w.status,401);const login=await call('auth',{action:'login',email:'client@test.com',password:'Strong-password-123'});assert.equal(login.status,200)});
await test('persistent file store preserves bytes',async()=>{const {nodeBucket}=await import('file://'+path.join(mod,'storage.mjs'));const b=nodeBucket(),buffer=new TextEncoder().encode('media');await b.put('safe-id',buffer.buffer);const read=await b.get('safe-id');assert.equal(await new Response(read.body).text(),'media');await assert.rejects(()=>b.get('../escape'))});
fs.rmSync(temp,{recursive:true,force:true});
