import {nodeDb,nodeBucket} from './storage';
import {sessionUser} from './auth';
export function config(){return process.env as Record<string,any>}
export function db(){return nodeDb()}
export function bucket(){return nodeBucket()}
export function fail(message:string,status=400):never{throw Object.assign(new Error(message),{status})}
export function identity(req:Request){const user=sessionUser(req);if(!user)fail('Entre na sua conta para continuar.',401);return user!}
export function sameOrigin(req:Request){const o=req.headers.get('origin');if(!o||o!==(process.env.APP_ORIGIN||new URL(req.url).origin))fail('Origem não permitida.',403)}
export async function brandAccess(req:Request,id:string,owner=false){const u=identity(req);const b:any=await db().prepare('SELECT * FROM brands WHERE id=?').bind(id).first();if(!b||(b.owner!==u.id&&(owner||b.email!==u.email)))fail('Acesso não permitido.',403);return {brand:b,user:u,isOwner:b.owner===u.id}}
export function respond(fn:(req:Request)=>Promise<Response>){return async(req:Request)=>{try{return await fn(req)}catch(e:any){const status=e.status||500;if(status===500)console.error('Request failed',e.message);return Response.json({error:status===500?'Não foi possível concluir. Tente novamente.':e.message},{status})}}}
export const uid=()=>crypto.randomUUID();
export async function crypt(value:string,decrypt=false){const secret=config().TOKEN_ENCRYPTION_KEY;if(!secret)fail('A proteção das integrações ainda não foi configurada.',503);const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt']);if(decrypt){const raw=Uint8Array.from(atob(value),c=>c.charCodeAt(0));return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:raw.slice(0,12)},key,raw.slice(12)))}const iv=crypto.getRandomValues(new Uint8Array(12));const out=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value)));return btoa(String.fromCharCode(...iv,...out))}
export function publicPost(p:any){return {...p,media:JSON.parse(p.media),history:JSON.parse(p.history)}}export function validatePost(v:any){if(typeof v.title!=='string'||!v.title.trim()||v.title.length>120)fail('Informe um título de até 120 caracteres.');if(typeof v.caption!=='string'||v.caption.length>2200)fail('A legenda deve ter até 2.200 caracteres.');if(!['instagram','facebook'].includes(v.platform))fail('Escolha a rede social.');if(!Array.isArray(v.media)||v.media.length>10)fail('Use até 10 mídias.');if(!['image','carousel','reel','story','text'].includes(v.format))fail('Formato inválido.');if(v.platform==='instagram'&&v.format==='text')fail('O Instagram precisa de imagem ou vídeo.');if(v.format==='story'&&v.platform!=='instagram')fail('Stories estão disponíveis apenas para Instagram.');const time=new Date(v.scheduled_at).getTime();if(!Number.isFinite(time)||time<Date.now()+60000||time>Date.now()+30*86400000)fail('Escolha uma data futura, até 30 dias a partir de hoje.');if(v.format==='image'&&v.media.length>1)fail('Para várias imagens, use carrossel.');if(v.format==='reel'&&v.media.length>1)fail('Use um vídeo por Reel.');if(v.format==='story'&&v.media.length>1)fail('Use uma mídia por Story.');if(v.platform==='facebook'&&v.format==='carousel')fail('Carrossel disponível para Instagram. No Facebook, use imagem, texto ou Reel.');const pollQuestion=typeof v.poll_question==='string'?v.poll_question.trim():'';const pollOptionA=typeof v.poll_option_a==='string'?v.poll_option_a.trim():'';const pollOptionB=typeof v.poll_option_b==='string'?v.poll_option_b.trim():'';if(v.has_poll||pollQuestion||pollOptionA||pollOptionB){if(v.platform!=='instagram'||v.format!=='story')fail('A enquete interativa está disponível apenas em Stories do Instagram.');if(!pollQuestion||pollQuestion.length>80||!pollOptionA||pollOptionA.length>24||!pollOptionB||pollOptionB.length>24)fail('Preencha a pergunta (até 80 caracteres) e as duas opções (até 24 caracteres cada).');if(v.media.length!==1)fail('Adicione uma única imagem ou vídeo para o Story com enquete.')}return {...v,poll_question:pollQuestion||null,poll_option_a:pollOptionA||null,poll_option_b:pollOptionB||null}}
