import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,readFileSync,readdirSync,existsSync,writeFileSync,renameSync,unlinkSync,createReadStream,statSync} from 'node:fs';
import {join} from 'node:path';
import {Readable} from 'node:stream';
const root=process.env.DATA_DIR||join(process.cwd(),'.data');
let database:DatabaseSync|undefined;
export function sqlite(){if(database)return database;mkdirSync(root,{recursive:true});const d=new DatabaseSync(join(root,'orbita.sqlite'));d.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');d.exec('CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY)');const folder=process.env.MIGRATIONS_DIR||join(process.cwd(),'drizzle');if(!existsSync(folder))throw new Error('Migration directory missing');for(const name of readdirSync(folder).filter(n=>n.endsWith('.sql')).sort()){if(d.prepare('SELECT name FROM _migrations WHERE name=?').get(name))continue;d.exec('BEGIN IMMEDIATE');try{d.exec(readFileSync(join(folder,name),'utf8'));d.prepare('INSERT INTO _migrations(name) VALUES(?)').run(name);d.exec('COMMIT')}catch(e){d.exec('ROLLBACK');throw e}}database=d;return d}
export function nodeDb(){return {prepare(query:string){const prepared=()=>sqlite().prepare(query);const bound=(values:any[]=[])=>({async first<T=any>():Promise<T|null>{return prepared().get(...values) as T||null},async all<T=any>():Promise<{results:T[]}>{return {results:prepared().all(...values) as T[]}},async run(){const r=prepared().run(...values);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}});return {...bound(),bind(...values:any[]){return bound(values)}}}}}
export function nodeBucket(){const path=(key:string)=>{if(!/^[a-zA-Z0-9_-]+$/.test(key))throw new Error('Invalid media key');return join(root,'uploads',key)};return {async put(key:string,bytes:ArrayBuffer,options?:any){mkdirSync(join(root,'uploads'),{recursive:true});const file=path(key),tmp=file+'.tmp';writeFileSync(tmp,Buffer.from(bytes));renameSync(tmp,file);return {key}},async get(key:string){const file=path(key);if(!existsSync(file))return null;return {body:Readable.toWeb(createReadStream(file)) as ReadableStream<Uint8Array>,size:statSync(file).size}},async delete(key:string){const file=path(key);if(existsSync(file))unlinkSync(file)}}}
