import {db,uid,config,brandAccess,respond,sameOrigin,fail,crypt} from '@/lib/server';
import {origin,graphVersion,saveConnection} from '@/lib/integrations';
export const GET=respond(async req=>{const brand=new URL(req.url).searchParams.get('brand_id')||'';await brandAccess(req,brand,true);const rows=(await db().prepare("SELECT account_id,name FROM connections WHERE brand_id=? AND provider LIKE 'candidate_%' AND expires>?").bind(brand,Date.now()).all()).results;return Response.json({accounts:rows})});
export const POST=respond(async req=>{sameOrigin(req);const provider=new URL(req.url).pathname.split('/').pop();if(!['meta','instagram','google'].includes(provider!))fail('Provedor inválido.');const v:any=await req.json(),a=await brandAccess(req,v.brand_id,true),c=config();if(v.account_id&&provider==='meta'){const row:any=await db().prepare("SELECT * FROM connections WHERE brand_id=? AND provider=? AND expires>?").bind(v.brand_id,'candidate_'+v.account_id,Date.now()).first();if(!row)fail('Autorização expirada. Conecte novamente.',409);const p=JSON.parse(await crypt(row.token,true));await saveConnection(v.brand_id,'facebook',p.id,p.name,p.access_token);if(p.instagram_business_account)await saveConnection(v.brand_id,'instagram',p.instagram_business_account.id,p.instagram_business_account.username||p.name,p.access_token);await db().prepare("DELETE FROM connections WHERE brand_id=? AND provider LIKE 'candidate_%'").bind(v.brand_id).run();return Response.json({ok:true})}
const appId=provider==='instagram'?(c.INSTAGRAM_APP_ID||c.META_APP_ID):c.META_APP_ID,appSecret=provider==='instagram'?(c.INSTAGRAM_APP_SECRET||c.META_APP_SECRET):c.META_APP_SECRET;
if(!c.TOKEN_ENCRYPTION_KEY||(provider==='meta'&&(!appId||!appSecret))||(provider==='instagram'&&(!appId||!appSecret))||(provider==='google'&&(!c.GOOGLE_CLIENT_ID||!c.GOOGLE_CLIENT_SECRET)))fail('Configure as credenciais do aplicativo para conectar a conta.',503);
const state=uid()+uid();await db().prepare('INSERT INTO oauth(state,user_id,brand_id,provider,expires) VALUES(?,?,?,?,?)').bind(state,a.user.id,v.brand_id,provider,Date.now()+600000).run();const redirect=origin()+'/api/oauth/'+provider;
const params=provider==='meta'?{client_id:appId,redirect_uri:redirect,state,response_type:'code',scope:'pages_show_list,pages_read_engagement,pages_manage_posts,instagram_basic,instagram_content_publish,instagram_manage_insights'}:provider==='instagram'?{client_id:appId,redirect_uri:redirect,state,response_type:'code',scope:'instagram_business_basic,instagram_business_content_publish,instagram_business_manage_insights',enable_fb_login:'0',force_authentication:'1'}:{client_id:c.GOOGLE_CLIENT_ID,redirect_uri:redirect,state,response_type:'code',scope:'https://www.googleapis.com/auth/calendar.app.created',access_type:'offline',prompt:'consent'};
const auth=provider==='meta'?'https://www.facebook.com/'+graphVersion()+'/dialog/oauth':provider==='instagram'?'https://www.instagram.com/oauth/authorize':'https://accounts.google.com/o/oauth2/v2/auth';
return Response.json({url:auth+'?'+new URLSearchParams(params as unknown as Record<string,string>)})});
